### ISSUE TITLE
Plugin does not work with PowerToys 0.79

### ISSUE THREAD

**Issue by Durus-R** [waaverecords/PowerToys-Run-Spotify#18]
It does show me the error "Fail to load plugin: Spotify"

I looked in the log and found the follwing entry:
```
[2024-03-05 10:37:28.8841] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::191]
-------------------------- Begin exception --------------------------
Message: Can't find class implement IPlugin for <Spotify> in C:\Users\smart\AppData\Local\Microsoft\PowerToys\PowerToys Run\Plugins\PowerToys-Run-Spotify\PowerToys-Run-Spotify.dll

Exception full name  : System.InvalidOperationException
Exception message    : Sequence contains no matching element
Exception stack trace:
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Wox.Plugin.PluginPair.CreatePluginInstance()
Exception source     : System.Linq
Exception target site: Void ThrowNoMatchException()
Exception HResult    : -2146233079
-------------------------- End exception --------------------------```

**Comment by waaverecords** [comment]
Fixed in https://github.com/waaverecords/PowerToys-Run-Spotify/releases/tag/v0.79.0.

**Comment by Durus-R** [comment]
Great! 
It's working now also for me. 
Have a nice day!
