### ISSUE TITLE
Search Results Not Consistently Displayed

### ISSUE THREAD

**Issue by xiaozhangup** [waaverecords/PowerToys-Run-Spotify#43]
I am experiencing an issue with the PowerToys Run Spotify plugin. The search functionality behaves inconsistently — sometimes it returns results as expected, but other times it does not return any results at all.
![image](https://github.com/user-attachments/assets/a13b893d-d1a0-4698-9941-9192a6eda8e9)
![image](https://github.com/user-attachments/assets/b8c802f2-7fb9-4ca3-a645-7db54c6d79d5)

![image](https://github.com/user-attachments/assets/d74949b9-956f-413b-bd99-d52b4c0f2c6c)
![image](https://github.com/user-attachments/assets/e6d020f2-0a59-42d3-8c20-165f0a3be12f)

**Comment by waaverecords** [comment]
Most likely a Spotify API issue.

**Comment by waaverecords** [comment]
You can also check logs for more information.

They should be located at.
%LocalAppData%\Microsoft\PowerToys\PowerToys Run\Logs

**Comment by xiaozhangup** [comment]
> You can also check logs for more information.
> 
> They should be located at. %LocalAppData%\Microsoft\PowerToys\PowerToys Run\Logs

`[2024-12-01 22:12:42.9129] [ERROR] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\Plugin\PluginManager.cs::240]
-------------------------- Begin exception --------------------------
Message: Exception for plugin <Spotify> when query <sp T>

Exception full name  : System.NullReferenceException
Exception message    : Object reference not set to an instance of an object.
Exception stack trace:
   at PowerToys_Run_Spotify.Main.<Query>b__24_3(SimplePlaylist playList) in C:\Users\m_sno\PowerToys-Run-Spotify\Main.cs:line 187
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at PowerToys_Run_Spotify.Main.Query(Query query) in C:\Users\m_sno\PowerToys-Run-Spotify\Main.cs:line 187
   at PowerLauncher.Plugin.PluginManager.<>c__DisplayClass23_0.<QueryForPlugin>b__0()
   at Wox.Infrastructure.Stopwatch.Debug(String message, Action action)
   at PowerLauncher.Plugin.PluginManager.QueryForPlugin(PluginPair pair, Query query, Boolean delayedExecution)
Exception source     : PowerToys-Run-Spotify
Exception target site: Wox.Plugin.Result <Query>b__24_3(SpotifyAPI.Web.SimplePlaylist)
Exception HResult    : -2147467261
-------------------------- End exception --------------------------


[2024-12-01 22:12:42.9252] [ERROR] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\Plugin\PluginManager.cs::240]
-------------------------- Begin exception --------------------------
Message: Exception for plugin <Spotify> when query <sp T>

Exception full name  : System.NullReferenceException
Exception message    : Object reference not set to an instance of an object.
Exception stack trace:
   at PowerToys_Run_Spotify.Main.<Query>b__24_3(SimplePlaylist playList) in C:\Users\m_sno\PowerToys-Run-Spotify\Main.cs:line 187
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at PowerToys_Run_Spotify.Main.Query(Query query) in C:\Users\m_sno\PowerToys-Run-Spotify\Main.cs:line 187
   at PowerLauncher.Plugin.PluginManager.<>c__DisplayClass23_0.<QueryForPlugin>b__0()
   at Wox.Infrastructure.Stopwatch.Debug(String message, Action action)
   at PowerLauncher.Plugin.PluginManager.QueryForPlugin(PluginPair pair, Query query, Boolean delayedExecution)
Exception source     : PowerToys-Run-Spotify
Exception target site: Wox.Plugin.Result <Query>b__24_3(SpotifyAPI.Web.SimplePlaylist)
Exception HResult    : -2147467261
-------------------------- End exception --------------------------


[2024-12-01 22:12:43.0330] [ERROR] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\Plugin\PluginManager.cs::240]
-------------------------- Begin exception --------------------------
Message: Exception for plugin <Spotify> when query <sp Tr>

Exception full name  : System.NullReferenceException
Exception message    : Object reference not set to an instance of an object.
Exception stack trace:
   at PowerToys_Run_Spotify.Main.<Query>b__24_3(SimplePlaylist playList) in C:\Users\m_sno\PowerToys-Run-Spotify\Main.cs:line 187
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at PowerToys_Run_Spotify.Main.Query(Query query) in C:\Users\m_sno\PowerToys-Run-Spotify\Main.cs:line 187
   at PowerLauncher.Plugin.PluginManager.<>c__DisplayClass23_0.<QueryForPlugin>b__0()
   at Wox.Infrastructure.Stopwatch.Debug(String message, Action action)
   at PowerLauncher.Plugin.PluginManager.QueryForPlugin(PluginPair pair, Query query, Boolean delayedExecution)
Exception source     : PowerToys-Run-Spotify
Exception target site: Wox.Plugin.Result <Query>b__24_3(SpotifyAPI.Web.SimplePlaylist)
Exception HResult    : -2147467261
-------------------------- End exception --------------------------


[2024-12-01 22:12:43.0484] [ERROR] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\Plugin\PluginManager.cs::240]
-------------------------- Begin exception --------------------------
Message: Exception for plugin <Spotify> when query <sp Tru>

Exception full name  : System.NullReferenceException
Exception message    : Object reference not set to an instance of an object.
Exception stack trace:
   at PowerToys_Run_Spotify.Main.<Query>b__24_3(SimplePlaylist playList) in C:\Users\m_sno\PowerToys-Run-Spotify\Main.cs:line 187
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at PowerToys_Run_Spotify.Main.Query(Query query) in C:\Users\m_sno\PowerToys-Run-Spotify\Main.cs:line 187
   at PowerLauncher.Plugin.PluginManager.<>c__DisplayClass23_0.<QueryForPlugin>b__0()
   at Wox.Infrastructure.Stopwatch.Debug(String message, Action action)
   at PowerLauncher.Plugin.PluginManager.QueryForPlugin(PluginPair pair, Query query, Boolean delayedExecution)
Exception source     : PowerToys-Run-Spotify
Exception target site: Wox.Plugin.Result <Query>b__24_3(SpotifyAPI.Web.SimplePlaylist)
Exception HResult    : -2147467261
-------------------------- End exception --------------------------


[2024-12-01 22:12:43.3305] [ERROR] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\Plugin\PluginManager.cs::240]
-------------------------- Begin exception --------------------------
Message: Exception for plugin <Spotify> when query <sp Tru>

Exception full name  : System.NullReferenceException
Exception message    : Object reference not set to an instance of an object.
Exception stack trace:
   at PowerToys_Run_Spotify.Main.<Query>b__24_3(SimplePlaylist playList) in C:\Users\m_sno\PowerToys-Run-Spotify\Main.cs:line 187
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at PowerToys_Run_Spotify.Main.Query(Query query) in C:\Users\m_sno\PowerToys-Run-Spotify\Main.cs:line 187
   at PowerLauncher.Plugin.PluginManager.<>c__DisplayClass23_0.<QueryForPlugin>b__0()
   at Wox.Infrastructure.Stopwatch.Debug(String message, Action action)
   at PowerLauncher.Plugin.PluginManager.QueryForPlugin(PluginPair pair, Query query, Boolean delayedExecution)
Exception source     : PowerToys-Run-Spotify
Exception target site: Wox.Plugin.Result <Query>b__24_3(SpotifyAPI.Web.SimplePlaylist)
Exception HResult    : -2147467261
-------------------------- End exception --------------------------


[2024-12-01 22:12:43.5808] [ERROR] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\Plugin\PluginManager.cs::240]
-------------------------- Begin exception --------------------------
Message: Exception for plugin <Spotify> when query <sp TruE>

Exception full name  : System.NullReferenceException
Exception message    : Object reference not set to an instance of an object.
Exception stack trace:
   at PowerToys_Run_Spotify.Main.<Query>b__24_3(SimplePlaylist playList) in C:\Users\m_sno\PowerToys-Run-Spotify\Main.cs:line 187
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at PowerToys_Run_Spotify.Main.Query(Query query) in C:\Users\m_sno\PowerToys-Run-Spotify\Main.cs:line 187
   at PowerLauncher.Plugin.PluginManager.<>c__DisplayClass23_0.<QueryForPlugin>b__0()
   at Wox.Infrastructure.Stopwatch.Debug(String message, Action action)
   at PowerLauncher.Plugin.PluginManager.QueryForPlugin(PluginPair pair, Query query, Boolean delayedExecution)
Exception source     : PowerToys-Run-Spotify
Exception target site: Wox.Plugin.Result <Query>b__24_3(SpotifyAPI.Web.SimplePlaylist)
Exception HResult    : -2147467261
-------------------------- End exception --------------------------


[2024-12-01 22:12:43.6182] [ERROR] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\Plugin\PluginManager.cs::240]
-------------------------- Begin exception --------------------------
Message: Exception for plugin <Spotify> when query <sp TruE>

Exception full name  : System.NullReferenceException
Exception message    : Object reference not set to an instance of an object.
Exception stack trace:
   at PowerToys_Run_Spotify.Main.<Query>b__24_3(SimplePlaylist playList) in C:\Users\m_sno\PowerToys-Run-Spotify\Main.cs:line 187
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at PowerToys_Run_Spotify.Main.Query(Query query) in C:\Users\m_sno\PowerToys-Run-Spotify\Main.cs:line 187
   at PowerLauncher.Plugin.PluginManager.<>c__DisplayClass23_0.<QueryForPlugin>b__0()
   at Wox.Infrastructure.Stopwatch.Debug(String message, Action action)
   at PowerLauncher.Plugin.PluginManager.QueryForPlugin(PluginPair pair, Query query, Boolean delayedExecution)
Exception source     : PowerToys-Run-Spotify
Exception target site: Wox.Plugin.Result <Query>b__24_3(SpotifyAPI.Web.SimplePlaylist)
Exception HResult    : -2147467261
-------------------------- End exception --------------------------


`

**Comment by xiaozhangup** [comment]
Seem is a bug of the plugin
'''
[2024-12-01 22:12:42.9129] [ERROR] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\Plugin\PluginManager.cs::240]
-------------------------- Begin exception --------------------------
Message: Exception for plugin <Spotify> when query <sp T>
Exception full name : System.NullReferenceException
Exception message : Object reference not set to an instance of an object.
Exception stack trace:
   at PowerToys_Run_Spotify.Main.<Query>b__24_3(SimplePlaylist playList) in C:\Users\m_sno\PowerToys-Run-Spotify\Main.cs:line 187
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at PowerToys_Run_Spotify.Main.Query(Query query) in C:\Users\m_sno\PowerToys-Run-Spotify\Main.cs:line 187
   at PowerLauncher.Plugin.PluginManager.<>c__DisplayClass23_0.<QueryForPlugin>b__0()
   at Wox.Infrastructure.Stopwatch.Debug(String message, Action action)
   at PowerLauncher.Plugin.PluginManager.QueryForPlugin(PluginPair pair, Query query, Boolean delayedExecution)
Exception source : PowerToys-Run-Spotify
Exception target site: Wox.Plugin.Result <Query>b__24_3(SpotifyAPI.Web.SimplePlaylist)
Exception HResult : -2147467261
-------------------------- End exception --------------------------
[2024-12-01 22:12:42.9252] [ERROR] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\Plugin\PluginManager.cs::240]
-------------------------- Begin exception --------------------------
Message: Exception for plugin <Spotify> when query <sp T>
Exception full name : System.NullReferenceException
Exception message : Object reference not set to an instance of an object.
Exception stack trace:
   at PowerToys_Run_Spotify.Main.<Query>b__24_3(SimplePlaylist playList) in C:\Users\m_sno\PowerToys-Run-Spotify\Main.cs:line 187
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at PowerToys_Run_Spotify.Main.Query(Query query) in C:\Users\m_sno\PowerToys-Run-Spotify\Main.cs:line 187
   at PowerLauncher.Plugin.PluginManager.<>c__DisplayClass23_0.<QueryForPlugin>b__0()
   at Wox.Infrastructure.Stopwatch.Debug(String message, Action action)
   at PowerLauncher.Plugin.PluginManager.QueryForPlugin(PluginPair pair, Query query, Boolean delayedExecution)
Exception source : PowerToys-Run-Spotify
Exception target site: Wox.Plugin.Result <Query>b__24_3(SpotifyAPI.Web.SimplePlaylist)
Exception HResult : -2147467261
-------------------------- End exception --------------------------
[2024-12-01 22:12:43.0330] [ERROR] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\Plugin\PluginManager.cs::240]
-------------------------- Begin exception --------------------------
Message: Exception for plugin <Spotify> when query <sp Tr>
Exception full name : System.NullReferenceException
Exception message : Object reference not set to an instance of an object.
Exception stack trace:
   at PowerToys_Run_Spotify.Main.<Query>b__24_3(SimplePlaylist playList) in C:\Users\m_sno\PowerToys-Run-Spotify\Main.cs:line 187
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at PowerToys_Run_Spotify.Main.Query(Query query) in C:\Users\m_sno\PowerToys-Run-Spotify\Main.cs:line 187
   at PowerLauncher.Plugin.PluginManager.<>c__DisplayClass23_0.<QueryForPlugin>b__0()
   at Wox.Infrastructure.Stopwatch.Debug(String message, Action action)
   at PowerLauncher.Plugin.PluginManager.QueryForPlugin(PluginPair pair, Query query, Boolean delayedExecution)
Exception source : PowerToys-Run-Spotify
Exception target site: Wox.Plugin.Result <Query>b__24_3(SpotifyAPI.Web.SimplePlaylist)
Exception HResult : -2147467261
-------------------------- End exception --------------------------
[2024-12-01 22:12:43.0484] [ERROR] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\Plugin\PluginManager.cs::240]
-------------------------- Begin exception --------------------------
Message: Exception for plugin <Spotify> when query <sp Tru>
Exception full name : System.NullReferenceException
Exception message : Object reference not set to an instance of an object.
Exception stack trace:
   at PowerToys_Run_Spotify.Main.<Query>b__24_3(SimplePlaylist playList) in C:\Users\m_sno\PowerToys-Run-Spotify\Main.cs:line 187
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at PowerToys_Run_Spotify.Main.Query(Query query) in C:\Users\m_sno\PowerToys-Run-Spotify\Main.cs:line 187
   at PowerLauncher.Plugin.PluginManager.<>c__DisplayClass23_0.<QueryForPlugin>b__0()
   at Wox.Infrastructure.Stopwatch.Debug(String message, Action action)
   at PowerLauncher.Plugin.PluginManager.QueryForPlugin(PluginPair pair, Query query, Boolean delayedExecution)
Exception source : PowerToys-Run-Spotify
Exception target site: Wox.Plugin.Result <Query>b__24_3(SpotifyAPI.Web.SimplePlaylist)
Exception HResult : -2147467261
-------------------------- End exception --------------------------
[2024-12-01 22:12:43.3305] [ERROR] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\Plugin\PluginManager.cs::240]
-------------------------- Begin exception --------------------------
Message: Exception for plugin <Spotify> when query <sp Tru>
Exception full name : System.NullReferenceException
Exception message : Object reference not set to an instance of an object.
Exception stack trace:
   at PowerToys_Run_Spotify.Main.<Query>b__24_3(SimplePlaylist playList) in C:\Users\m_sno\PowerToys-Run-Spotify\Main.cs:line 187
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at PowerToys_Run_Spotify.Main.Query(Query query) in C:\Users\m_sno\PowerToys-Run-Spotify\Main.cs:line 187
   at PowerLauncher.Plugin.PluginManager.<>c__DisplayClass23_0.<QueryForPlugin>b__0()
   at Wox.Infrastructure.Stopwatch.Debug(String message, Action action)
   at PowerLauncher.Plugin.PluginManager.QueryForPlugin(PluginPair pair, Query query, Boolean delayedExecution)
Exception source : PowerToys-Run-Spotify
Exception target site: Wox.Plugin.Result <Query>b__24_3(SpotifyAPI.Web.SimplePlaylist)
Exception HResult : -2147467261
-------------------------- End exception --------------------------
[2024-12-01 22:12:43.5808] [ERROR] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\Plugin\PluginManager.cs::240]
-------------------------- Begin exception --------------------------
Message: Exception for plugin <Spotify> when query <sp TruE>
Exception full name : System.NullReferenceException
Exception message : Object reference not set to an instance of an object.
Exception stack trace:
   at PowerToys_Run_Spotify.Main.<Query>b__24_3(SimplePlaylist playList) in C:\Users\m_sno\PowerToys-Run-Spotify\Main.cs:line 187
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at PowerToys_Run_Spotify.Main.Query(Query query) in C:\Users\m_sno\PowerToys-Run-Spotify\Main.cs:line 187
   at PowerLauncher.Plugin.PluginManager.<>c__DisplayClass23_0.<QueryForPlugin>b__0()
   at Wox.Infrastructure.Stopwatch.Debug(String message, Action action)
   at PowerLauncher.Plugin.PluginManager.QueryForPlugin(PluginPair pair, Query query, Boolean delayedExecution)
Exception source : PowerToys-Run-Spotify
Exception target site: Wox.Plugin.Result <Query>b__24_3(SpotifyAPI.Web.SimplePlaylist)
Exception HResult : -2147467261
-------------------------- End exception --------------------------
[2024-12-01 22:12:43.6182] [ERROR] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\Plugin\PluginManager.cs::240]
-------------------------- Begin exception --------------------------
Message: Exception for plugin <Spotify> when query <sp TruE>
Exception full name : System.NullReferenceException
Exception message : Object reference not set to an instance of an object.
Exception stack trace:
   at PowerToys_Run_Spotify.Main.<Query>b__24_3(SimplePlaylist playList) in C:\Users\m_sno\PowerToys-Run-Spotify\Main.cs:line 187
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at PowerToys_Run_Spotify.Main.Query(Query query) in C:\Users\m_sno\PowerToys-Run-Spotify\Main.cs:line 187
   at PowerLauncher.Plugin.PluginManager.<>c__DisplayClass23_0.<QueryForPlugin>b__0()
   at Wox.Infrastructure.Stopwatch.Debug(String message, Action action)
   at PowerLauncher.Plugin.PluginManager.QueryForPlugin(PluginPair pair, Query query, Boolean delayedExecution)
Exception source : PowerToys-Run-Spotify
Exception target site: Wox.Plugin.Result <Query>b__24_3(SpotifyAPI.Web.SimplePlaylist)
Exception HResult : -2147467261
-------------------------- End exception --------------------------


'''


---- Replied Message ----
| From | Michael ***@***.***> |
| Date | 12/1/2024 22:11 |
| To | ***@***.***> |
| Cc | Daniel ***@***.***>,
***@***.***> |
| Subject | Re: [waaverecords/PowerToys-Run-Spotify] Search Results Not Consistently Displayed (Issue #43) |

You can also check logs for more information.

They should be located at.
%LocalAppData%\Microsoft\PowerToys\PowerToys Run\Logs

**Comment by xiaozhangup** [comment]
Seems to be an issue with the plugin?

**Comment by waaverecords** [comment]
Seems like the Spotify API changed.

https://github.com/JohnnyCrazy/SpotifyAPI-NET/issues/1012

**Comment by xiaozhangup** [comment]
Are you planning to create multilingual support? I can provide the Chinese translation

**Comment by SwastikGorai** [comment]
Spotify did change its API terms, now it will be restricting access to third-party 😢

**Comment by waaverecords** [comment]
Fixed in [v0.86.0-2](https://github.com/waaverecords/PowerToys-Run-Spotify/releases/tag/v0.86.0-2).
